### PR TITLE
close #342: add a page to describe how to use Gradle plugin

### LINKED ISSUE #342: [docs][suggestion] Explain how to run gradle plugin
Hi,

I was trying to run Spotbugs as a complete newbie and one fundamental problem after adding Spotbugs configuration to my build.gradle was "how to actually run the gradle plugin". 

Maybe it would be worth adding a sentence explaining this to http://spotbugs.readthedocs.io/en/latest/migration.html or any other page of the documentation.

Best regards,
Martin

### PR DESCRIPTION
**Pull request by KengoTODA**
Just added a page to describe how to use Gradle plugin.

### CODE REVIEW

**Comment by MartyIX** [comment]
* typo: `so you can simly run` -> simply
* typo:  spotbugsMain and spotbugsTest -> missing closing backticks

**Comment by KengoTODA** [comment]
Thanks @MartyIX, I've fixed them.

**Comment by KengoTODA** [comment]
staging site for this PR is [here](http://spotbugs-in-kengo-toda.readthedocs.io/en/docs-for-gradle-plugin/gradle.html)

**Comment by KengoTODA** [comment]
Hi @iloveeclipse, can I ask you to review & merge this PR?

**Comment by KengoTODA** [comment]
@iloveeclipse yes .po file is necessary, for coming i18n.

http://www.sphinx-doc.org/en/stable/intl.html

**Comment by KengoTODA** [comment]
Thank you!

**Pull request merged**
