### PR TITLE
handle long constant values in the OpcodeStack

### PR DESCRIPTION
**Pull request by mebigfatguy**
processing of "J" (long value constants ) was not processed, so added. Also changed code to switch rather than if/else chain.
----

Make sure these boxes are checked before submitting your PR -- thank you!

- [ ] Added an entry into `CHANGELOG.md` if you have changed SpotBugs code
- [ ] Added an entry into `gradlePlugin/CHANGELOG.md` if you have changed Gradle plugin code

### CODE REVIEW

**Comment by iloveeclipse** [comment]
Dave, few questions:
- do you have a use case for that, where we fail to interpret long constants?
- could you add a test case?
- looks like the change can go first to 3.1 branch, because it contains a fix only?

**Comment by mebigfatguy** [comment]
I just found it thru inspection, but i can probably cook up a test case. and 3.1 is fine.

**Comment by KengoTODA** [comment]
I changed base branch to `release-3.1`, please solve conflict.

**Comment by KengoTODA** [comment]
@mebigfatguy ping

**Comment by KengoTODA** [comment]
Created #688 to merge this change, please refer that

**Pull request closed without merging**
