### PR TITLE
Fix #1472 SA_LOCAL_SELF_COMPUTATION bug

### LINKED ISSUE #1472: SA_LOCAL_SELF_COMPUTATION bug
Hi,
I read [SA_LOCAL_SELF_COMPUTATION](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#sa-nonsensical-self-computation-involving-a-variable-e-g-x-x-sa-local-self-computation) on SpotBugs Bug Description page, which mentions that this method performs a nonsensical computation of a local variable with another reference to the same variable (e.g., `x&x` or `x-x`).
So, I wrote test cases as below.
```java
int testSA_LOCAL_SELF_COMPUTATION(){
      int flags = 1;
      return flags ^ flags; // warning SA_LOCAL_SELF_COMPUTATION
  }

  int testSA_LOCAL_SELF_COMPUTATION1(){
      int flags = 1;
      return flags & flags; // no warning (False negative)
  }

  int testSA_LOCAL_SELF_COMPUTATION2(){
      int flags = 1;
      return flags - flags; // no warning (False negative)
  }

  int testSA_LOCAL_SELF_COMPUTATION3(){
      int flags = 1;
      return flags | flags; // no warning (False negative)
  }

```

It can be seen from the results that only `^` will trigger SpotBugs to report **SA_LOCAL_SELF_COMPUTATION**, while other operators will not. 

I tried to search test cases of **SA_LOCAL_SELF_COMPUTATION** in SpotBugs source code and found several test cases of  **SA_FIELD_SELF_COMPUTATION** which detect self computation of **field** instead of **local variables**.
Similar test-cases for **SA_FIELD_SELF_COMPUTATION** executed and all four output **SA_FIELD_SELF_COMPUTATION** errors report.
```java
int x = 1;
  int testSA_FIELD_SELF_COMPUTATION(){
      return x ^ x; // warning SA_FIELD_SELF_COMPUTATION
  }

  int testSA_FIELD_SELF_COMPUTATION1(){
      return x & x; // warning SA_FIELD_SELF_COMPUTATION
  }

  int testSA_FIELD_SELF_COMPUTATION2(){
      return x - x; // warning SA_FIELD_SELF_COMPUTATION
  }

  int testSA_FIELD_SELF_COMPUTATION3(){
      return x | x; // warning SA_FIELD_SELF_COMPUTATION
  }
```

Finally, I realized that the fault is in line **325** of [FindSelfComparison.java](https://github.com/spotbugs/spotbugs/blob/a6f9acb2932b54f5b70ea8bc206afb552321a222/spotbugs/src/main/java/edu/umd/cs/findbugs/detect/FindSelfComparison.java#L325).
```java
else if (opCode == Const.IXOR && item0.sameValue(item1)) {
```
The code shows that SpotBugs reports **SA_FIELD_SELF_COMPUTATION** only when `opCode` equals `Const.IXOR`(`^`).

It is so confusing that self computation detection of `local variables` only including `^` operator while the detection of `field` supports much more. Is it a bug?

### PR DESCRIPTION
**Pull request by gloNelson**
Hi,
Fixes #1472
I modified the problematic code line in `spotbugs/src/main/java/edu/umd/cs/findbugs/detect/FindSelfComparison.java`.
Test-cases mentioned in #1472 are added in `spotbugsTestCases/src/java/ghIssues/Issue1472.java` and `spotbugs-tests/src/test/java/edu/umd/cs/findbugs/detect/Issue1472Test.java`.  

----

Make sure these boxes are checked before submitting your PR -- thank you!

- [x] Added an entry into `CHANGELOG.md` if you have changed SpotBugs code

### CODE REVIEW

**Comment by gloNelson** [comment]
> It seems that [f7c6735](https://github.com/spotbugs/spotbugs/commit/f7c67352d2ff639c3b73e60b0a9fe5bc1b208ea8) moved the support for `ISUB` bytecode to [FindSelfComparison2.java](https://github.com/spotbugs/spotbugs/blob/a6f9acb2932b54f5b70ea8bc206afb552321a222/spotbugs/src/main/java/edu/umd/cs/findbugs/detect/FindSelfComparison2.java#L147) and a new class uses the same bug type `SA_LOCAL_SELF_COMPURATION` to report it. Could you rerun the test with `FindSelfComparison2`?

@KengoTODA 
I had rerun the [test](https://github.com/spotbugs/spotbugs/issues/1472) of **SA_LOCAL_SELF_COMPUTATION** with `FindSelfComparison2`.
```java
int testSA_LOCAL_SELF_COMPUTATION(){
    int flags = 1;
    return flags ^ flags; // warning SA_LOCAL_SELF_COMPUTATION
}

int testSA_LOCAL_SELF_COMPUTATION1(){
    int flags = 1;
    return flags & flags; // no warning (False negative)
}

int testSA_LOCAL_SELF_COMPUTATION2(){
    int flags = 1;
    return flags - flags; // no warning (False negative)
}

int testSA_LOCAL_SELF_COMPUTATION3(){
    int flags = 1;
    return flags | flags; // no warning (False negative)
}
```
I created a maven project - [SpotBugs-Issue1472-Test](https://github.com/gloNelson/SpotBugs-Issue1472-Test) to test with `FindSelfComparison2`.

My `pom.xml`
```
<plugin>
      <groupId>com.github.spotbugs</groupId>
      <artifactId>spotbugs-maven-plugin</artifactId>
      <version>4.2.2</version>
      <configuration>
          <visitors>FindSelfComparison, FindSelfComparison2</visitors>
          <!--<visitors>FindSelfComparison2</visitors>-->
      </configuration>
      <dependencies>
          <!-- overwrite dependency on spotbugs if you want to specify the version of spotbugs -->
          <dependency>
              <groupId>com.github.spotbugs</groupId>
              <artifactId>spotbugs</artifactId>
              <version>4.2.2</version>
          </dependency>
      </dependencies>
  </plugin>
```
It can be seen from my `pom.xml` that two configurations are set to check whether `FindSelfComparison2` is to do with my test-cases.

The outputs including [visitor(FindSelfComparison,FindSelfComparison2).log](https://github.com/gloNelson/SpotBugs-Issue1472-Test/blob/master/output/visitor(FindSelfComparison%2CFindSelfComparison2).log) and [visitor(FindSelfComparison2).log](https://github.com/gloNelson/SpotBugs-Issue1472-Test/blob/master/output/visitor(FindSelfComparison2).log) are uploaded.

The SpotBugs detected a **SA_LOCAL_SELF_COMPUTATION** bug instance when setting `<visitors>FindSelfComparison, FindSelfComparison2</visitors>`, but no error was found under another configuration.

**Review by KengoTODA — APPROVED** [review]
Confirmed that both `FindSelfComparison` and `FindSelfComparison2` cannot work as expected. This PR is needed to fix.

**Comment by KengoTODA** [comment]
@gloNelson could you resolve the conflict? Then I will merge this PR and release a new patch version in the next month.

**Comment by gloNelson** [comment]
The conflict has been solved in #1478.

**Pull request closed without merging**
