### PR TITLE
[docs] Fix css for multiple lines code

### PR DESCRIPTION
**Pull request by KengoTODA**
staging site: http://spotbugs-in-kengo-toda.readthedocs.io/en/fix-css-for-multiple-lines-code/bugDescriptions.html

cc: @orihalcon128

### CODE REVIEW

**Comment by orihalcon128** [comment]
LGTM

**Comment by KengoTODA** [comment]
Hi @iloveeclipse, can I ask you to review & merge this PR?

**Comment by iloveeclipse** [comment]
Sorry for the delay, I'm on vacation with limited connection right now.

**Comment by KengoTODA** [comment]
Thanks for your review, and have a nice vacation!

**Pull request merged**
