### PR TITLE
Release 4.8.3

### PR DESCRIPTION
**Pull request by JuditKnoll**
This PR will trigger the release 4.8.3.
I haven't got permission yet to the project in the [SonaType Nexus](https://oss.sonatype.org/), and the [Eclipse MarketPlace page](https://marketplace.eclipse.org/content/spotbugs-eclipse-plugin). So, if someone could help with the manual parts of the release process on these two sites, I would be really grateful.

----

Make sure these boxes are checked before submitting your PR -- thank you!

- [X] Added an entry into `CHANGELOG.md` if you have changed SpotBugs code

### CODE REVIEW

**Comment by JuditKnoll** [comment]
It looks like pushing a tag to any branch in the spotbugs/spotbugs repository creates a release. IMO it would be better, if the `release.yml` script was modified to only release from the master branch, or at least we document this behavior into the `RELEASE_PROCEDURE.md`. I wanted to wait for a few smaller PRs yet, and also an approve for this PR. I'm sorry for the problems.

**Comment by JuditKnoll** [comment]
Meanwhile I received permission to the nexus repository manager, so I could release to the maven central from staging, but I don't think it's a good idea until this PR is merged to master, which is blocked because there is no approving review.
@hazendaz I would really appreciate your help here. Thank you in advance.

**Review by hazendaz — APPROVED** [review]

**Comment by hazendaz** [comment]
@JuditKnoll Its merged now, you should be able to proceed.  I do agree with you the actions need cleaned up so it doesn't just run from anywhere.  Although I like your approach to use release branch and letting that happen there.

**Comment by JuditKnoll** [comment]
Thank you very much. I released the closed staging repository from [Nexus](https://oss.sonatype.org/), the directory for it haven't appeared yet in the [maven repo](https://repo1.maven.org/maven2/com/github/spotbugs/spotbugs/), but the [maven-metadata.xml](https://repo1.maven.org/maven2/com/github/spotbugs/spotbugs/maven-metadata.xml) already knows about the new version. So I think it only takes some time now.
If I'm not mistaken, the only thing left is updating the version in the Eclipse MarketPlace.

**Comment by gtoison** [comment]
Is there really a need for the final steps in Nexus to be manual?
For the SpotBugs sonar plugin the build automically pushes the new version, there's no need to close the staging

**Comment by hazendaz** [comment]
For sonatype, staging is auto closed just not released.  it can be automated.  Do you happen to know what does that in the other project that can be then applied to this one?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gtoison** [comment]
For a maven project:

```
          <plugin>
            <groupId>org.sonatype.plugins</groupId>
            <artifactId>nexus-staging-maven-plugin</artifactId>
            <version>1.6.13</version>
            <extensions>true</extensions>
            <configuration>
               <serverId>ossrh</serverId>
               <nexusUrl>https://oss.sonatype.org/</nexusUrl>
               <autoReleaseAfterClose>true</autoReleaseAfterClose>
            </configuration>
          </plugin>
```

For `https://github.com/gradle-nexus/publish-plugin`, as far as I understand we would need to call `closeAndReleaseSonatypeStagingRepository`

**Comment by JuditKnoll** [comment]
> Is there really a need for the final steps in Nexus to be manual? For the SpotBugs sonar plugin the build automically pushes the new version, there's no need to close the staging

I think initially it may have come from the suggestion from the [Gradle Nexus Publish Plugin](https://github.com/gradle-nexus/publish-plugin#add-metadata)'s Readme:
> Please bear in mind that - especially on the initial project publishing to Maven Central - it might be wise to call just `publishToSonatype closeSonatypeStagingRepository` and manually verify that the artifacts placed in the closed staging repository in Nexus looks ok. After that, the staging repository might be dropped (if needed) or manually released from the Nexus UI.

In it's current form, I also don't see any reason to keep it this way. Even the release process documentation states, that the publish is done automatically.
It looks like it was added originally like this (see https://github.com/spotbugs/spotbugs/pull/1649), it wasn't mentioned why not release automatically.

**Comment by hazendaz** [comment]
if you got it handled on how to switch it to automatic, I'd say go for it.  There is a side benefit if that is automated.  The next time we give someone release access writes, we won't have to have them actually sign up at sonatype.  I can see how that would have saved some troubles here.  But do see this everywhere now. I'll try to get the maven plugin out and gradle too in nest few days.  Thanks for giving this a shot.  No clue on what is done over on Eclipse Marketplace but believe @iloveeclipse knows about how to address marketplace!

**Comment by JuditKnoll** [comment]
There is a problem with the release tag, it's not on master.
- it exists on the [appropriate commit](https://github.com/spotbugs/spotbugs/pull/2765/commits/1e42fc91cda54fd0aff65ab5a90d3b6d3f079aaa) of the PR;
    - commit hash: 1e42fc91cda54fd0aff65ab5a90d3b6d3f079aaa
- when we go to the commits of the 4.8.3 tag, it's also in the right place: https://github.com/spotbugs/spotbugs/commits/4.8.3/
    - but "the commit does not belong to any branch on this repository"
    - commit hash: 1e42fc91cda54fd0aff65ab5a90d3b6d3f079aaa
- the appropriate [commit on the master](https://github.com/spotbugs/spotbugs/commit/f979bfb38b2705cb2038b00d4da0ced30bbacab4) does not contain the tag, since it has different commit hash,
     - commit hash: f979bfb38b2705cb2038b00d4da0ced30bbacab4

I think it's because the PR was merged with rebase, which changed the commit id. But it needed to be merged with rebase, otherwise it would have been a squash merge, which also doesn't keep the commit id, since merge commits are not enabled for the repository. The commit id could have been kept by cherrypicking the commit, but that's not the best idea with PRs IMO.

If we delete and push the tag to master to the correct commit, that will trigger the release process one more time, and could cause some issues. I think if we disabled the workflows for the time of pushing the tag, then enabled again, that could solve the issue without any additional problems. Does anyone have a better idea than this?

From now on, the release tags should only be pushed to master, and this should be documented in the release process, and the `release.yml` modified to prevent it from happening again. AFAIK currently there is no easy way provided in the GitHub Actions to check the branch when a tag is pushed (see https://github.com/orgs/community/discussions/5251), only some workarounds.

This may be the same issue as the one with the release-3.1 branch (see Branch Cleanup discussion https://github.com/spotbugs/spotbugs/discussions/2614).

**Comment by hazendaz** [comment]
@JuditKnoll Its fixed.  Yes it would happen from the rebase.  How I have been doing it to avoid messing that up is just raising a PR so others see it then pushing directly to master.  At any rate, the tag was there, it didn't need to turn off the tag but did that to be safe.  When I pulled I got the tag from the remote even before that so it was there, just not where you wanted it.  So I merged that specific commit back into master, discarded the conflicts and pushed.

**Comment by hazendaz** [comment]
@gtoison Thanks for hint, I still am weak on gradle, do you understand what needs added?  Maybe you can add it?

**Comment by gtoison** [comment]
I don't know gradle that well and couldn't test my change, but I've submitted a PR with what I _think_ should do the trick: https://github.com/spotbugs/spotbugs/pull/2775

**Comment by JuditKnoll** [comment]
> @JuditKnoll Its fixed. Yes it would happen from the rebase. How I have been doing it to avoid messing that up is just raising a PR so others see it then pushing directly to master. At any rate, the tag was there, it didn't need to turn off the tag but did that to be safe. When I pulled I got the tag from the remote even before that so it was there, just not where you wanted it. So I merged that specific commit back into master, discarded the conflicts and pushed.

Thank you very much for your help 😄

**Pull request merged**
