### PR TITLE
[doc] Add document to help Android developers

### PR DESCRIPTION
**Pull request by KengoTODA**
This document helps Android developer to avoid problem like #423.

@johnscancella @jsotuyod Do you know in which timing we can validate Gradle Plugin configuration? If we can throw error with reasonable message (e.g. please set `destination` for SpotBugs report), it should be better solution.

### CODE REVIEW

**Comment by johnscancella** [comment]
I would recommend putting it in the SpotBugsSpecBuilder, somewhere around here:
https://github.com/spotbugs/spotbugs/blob/master/gradlePlugin/src/main/java/com/github/spotbugs/internal/spotbugs/SpotBugsSpecBuilder.java#L166

**Comment by KengoTODA** [comment]
Wmm, it seems that Gradle throws exception before it reaches to `SpotBugsSpecBuilder`.

It seems that Gradle plugin verify config in `project.afterEvaluate`, I will have a try.

https://android.googlesource.com/platform/tools/base/+/android-7.0.0_r34/build-system/gradle/src/main/groovy/com/android/build/gradle/BasePlugin.java#574

**Comment by johnscancella** [comment]
Looks good to me. I would only suggest editing the phrasing a little bit. So instead of 
> Task '%s' has no destination for TEXT report. Set reports.text.destination to this task.

I would change it to something like:
> Task '%s' has no destination for TEXT report. Please set the reports.text.destination for this task or in the spotbugs configuration closure.

**Comment by KengoTODA** [comment]
@johnscancella 

> spotbugs configuration closure

Do you mean `spotbugs { ... }`? In my understanding it does not support report configuration.

http://gradle.monochromeroad.com/docs/dsl/org.gradle.api.plugins.quality.FindBugsExtension.html

**Comment by johnscancella** [comment]
Sorry I can't look at the link right now, for some reason my employer is blocking it.

Since it a direct copy from Gradle's findbugs implementation it should be the same as their example https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.FindBugsExtension.html#org.gradle.api.plugins.quality.FindBugsExtension:reportsDir

so you should be able to do 
```
spotbugs{
  reportsDir = file("$rootProject.projectDir/build/reports/MY_REPORT_DIR")
}
```

**Comment by KengoTODA** [comment]
@johnscancella Yes extension (closure) supports setting `reportsDir`, not name of report file. To configure report file name, user needs to set property of Task.

Note that basically user does not need to configure report name, because SpotBugs Gradle Plugin uses name of sourceSet by default (e.g. `main.xml` for `main` sourceSet). In the reported case, user @LintaoLin had to set manually, because his project had no sourceSet. This is reproducible case for Android hackers so I wanna suggest us to enhance error message.

**Comment by johnscancella** [comment]
@KengoTODA ok, that makes sense. But looking at the code that is in the pull request it all refers to the report destination, not report name.  is `reports.text.destination` used for the report name as well?

**Comment by KengoTODA** [comment]
@johnscancella Yes for our plugin. Refer [SpotBugsSpecBuilder](https://github.com/spotbugs/spotbugs/blob/3.1.0_RC6/gradlePlugin/src/main/java/com/github/spotbugs/internal/spotbugs/SpotBugsSpecBuilder.java#L165-L166) and [Gradle API Javadoc](http://gradle.monochromeroad.com/docs/javadoc/org/gradle/api/reporting/Report.html#getDestination--) for detail.

**Comment by KengoTODA** [comment]
@members please review and approve this change. Thanks in advance!

**Pull request merged**
