### PR TITLE
Update gradle and plugins to prepare for JDK 11

### PR DESCRIPTION
**Pull request by KengoTODA**
Before we introduce Gradle 5.0 and CI build on oraclejdk11, we need to bump up several tools:

* Gradle, to reduce difference between our current build and Gradle 5.0
* Mockito and jacoco, to prepare to handle Java 11 binaries
* spotbugs-gradle-plugin, to support latest Gradle

This PR is related with #763.
After we successfully merge this PR, I will create another that introduces Gradle 5.0 RC1 and oraclejdk11.

### CODE REVIEW

**Comment by ThrawnCA** [comment]
Remind me again, which JDK version do we require? Because I suspect that the dependencies of Mockito 2.23 will choke on less than JDK 9.

**Comment by KengoTODA** [comment]
As explained at #763, JDK 7 is not supported, then JDK 8 and above should be target.

Then I think we can focus on JDK 8 and 11. [Java 9 and 10 are already unsupported](https://www.oracle.com/technetwork/java/javase/eol-135779.html) so we can stop support on them.

**Comment by KengoTODA** [comment]
> the dependencies of Mockito 2.23 will choke on less than JDK 9.

Could you share more info about this? I cannot find in [their release note](https://github.com/mockito/mockito/blob/release/2.x/doc/release-notes/official.md#2230).

**Comment by ThrawnCA** [comment]
> > the dependencies of Mockito 2.23 will choke on less than JDK 9.
> 
> Could you share more info about this? I cannot find in [their release note](https://github.com/mockito/mockito/blob/release/2.x/doc/release-notes/official.md#2230).

Version 2.22.1 makes note of a Byte-Buddy update for JDK 11 support. I've tripped over this in other projects using JDK 8 and Jetty 9.2; when Jetty starts, it chokes on the newer Byte Buddy.

It might or might not be a problem here, just thought I'd bring it up.

**Comment by wreulicke** [comment]
CI passed. 🎉

**Comment by KengoTODA** [comment]
> It might or might not be a problem here, just thought I'd bring it up.

Got it. I think it is not be a problem in our case, at least test passes as usual.

**Comment by KengoTODA** [comment]
@spotbugs/everyone please review and approve this PR, thanks in advance!

**Pull request merged**
