### PR TITLE
Add CheckLogParamNum detector for slf4j. #587

### PR DESCRIPTION
**Pull request by guoxiangbin**
Add CheckLogParamNum detector for slf4j. #587 
Check if placeholder correct when call log.[info|error|warn|debug|trace].
When the first parameter is a formatted string, and the number of braces in it does not match the number of formatted parameters, report a bug.

---
This is the first time I submit my code on GitHub. If there is any mistake, I hope I can get your help.

----

Make sure these boxes are checked before submitting your PR -- thank you!

- [x] Added an entry into `CHANGELOG.md` if you have changed SpotBugs

### CODE REVIEW

**Comment by KengoTODA** [comment]
This detector is duplicated with `LO_INCORRECT_NUMBER_OF_ANCHOR_PARAMETERS` in fb-contrib and `SLF4J_PLACE_HOLDER_MISMATCH` in findbugs-slf4j. I personally recommend you to use them, because they are already tested during long time.

**Comment by guoxiangbin** [comment]
Thank you for your reply. I can't search the two detectors you're talking about in the spotbugs project, and I can't detect the bug in my test case under the default configuration. I am very eager to get detailed instructions on the use of them.

**Comment by KengoTODA** [comment]
Just install https://kengotoda.github.io/findbugs-slf4j/ or https://github.com/mebigfatguy/fb-contrib then they'll trigger additional detectors provided by plugins.

The procedure to install plugin depends on how you run spotbugs. For instance, if you're using gradle, check [this manual page](http://spotbugs.readthedocs.io/en/latest/gradle.html#introduce-spotbugs-plugin) for detail.

**Comment by guoxiangbin** [comment]
Thank you very much. I'll try to use them. By the way, Is there a detector that detects the problem of synchronized on local variables? #590

**Comment by guoxiangbin** [comment]
This detector is duplicated with LO_INCORRECT_NUMBER_OF_ANCHOR_PARAMETERS in fb-contrib and SLF4J_PLACE_HOLDER_MISMATCH in findbugs-slf4j.

**Pull request closed without merging**
