### PR TITLE
Generics enhancements

### PR DESCRIPTION
**Pull request by gtoison**
Variable types such as `<C extends Collection<String>>` are not analyzed correctly because they are not parsed from the method signature as noted in #608

### CODE REVIEW

**Comment by gtoison** [comment]
- Backported JEP's 457 (classfile API) signature parser to support more generics use cases, such as type variables
- The backported code is a subset of the classfile API (the signatures parser), most of the changes relate to records, switches and sealed interfaces
- The new signature parser does not handle invalid signatures produced by older Eclipse JDT versions
- Parsing a signature might require the method and type signatures to locate variable types, some of the code still uses the old parser and could be updated in further enhancements
- GenericObjectType.variable was used for the variable type identifier OR for the wildcard indicator (extends/super), added a wildcard indicator field
- Let GenericObjectType have several extensions (for instance <P extends InterfaceA & InterfaceB>)
- Modified GenericObjectType equals and toString to handle self-referencing types (e.g. <C extends Map<X, C>>)
- In particular GenericObjectType.toString() is modified to return the bytecode signature when available

**Comment by gtoison** [comment]
I think the failed smoke tests are because spotbugs analyzes itself using the Gradle plugin, which isn't incorporating the changes to support `<C extends Collection<String>>`.
On my computer `gradlew clean test` shows the same error while `gradlew test`
I tried modifying the Gradle build to fix this but can't seem to understand how it works. Would anyone know?

**Comment by gtoison** [comment]
Regarding the backport of the classfile API, the license seems to be GNU GPL2 so it seems allowed to me to modify the sources and include them in SpotBugs.
I've not looked much into the rest of the API but there might other useful things.
This is meant to be temporary as we will eventually require a >21 JDK version but realistically this backport would stay for several years.

**Comment by iloveeclipse** [comment]
> the license seems to be GNU GPL2 so it seems allowed to me to modify the sources and include them in SpotBugs.

You can't and should not add *any* modified GPL licensed code to SpotBugs as it would require SpotBugs to use GPL and that in turn would be a breaking change because SpotBugs uses *LGPL* and so our users/adopters are *not* forced to open source all their code.

**Review by iloveeclipse — CHANGES_REQUESTED** [review]
Adding GPL'ed code, especially the one from Oracle is not possible, sorry.

As much as I would like to see any enhancement, I can't agree on changing SpotBugs license to GPL.

**Comment by gtoison** [comment]
What about using this backport of the classfile Api https://github.com/dmlloyd/jdk-classfile-preview ?

**Comment by iloveeclipse** [comment]
> What about using this backport of the classfile Api https://github.com/dmlloyd/jdk-classfile-preview ?

Same license as before, same Oracle origin GPL code.

**Comment by gtoison** [comment]
But doesn't it fall under the classpath exception? After all we are using the base java library under that exception. Or do you mean that the exception does not transfer to separately released modified code?

**Comment by iloveeclipse** [comment]
See https://opensource.stackexchange.com/questions/1410/what-is-the-difference-between-gpl-classpath-exception-vs-lgpl

LGPL allows is to modify the original code **and** ship that, GPL + classpath doesn't.

**Comment by iloveeclipse** [comment]
Beside GPL/LGPL license question, I'm not a lawyer, but I would not embed **any** modified Oracle code to SpotBugs in general, rememberimg Oracle vs Google lawsuit and how Oracle lawyers argued about trivial code snippets etc.

**Pull request closed without merging**
