### PR TITLE
Update ASM to 6.1 to support Java 10 class files

### PR DESCRIPTION
**Pull request by cheister**
Related to https://github.com/spotbugs/spotbugs/issues/593

Release Notes for ASM: http://asm.ow2.org/history.html

Significant update 
  - new V10 constant for Java 10 class files

----

Make sure these boxes are checked before submitting your PR -- thank you!

- [ X] Added an entry into `CHANGELOG.md` if you have changed SpotBugs code

### CODE REVIEW

**Comment by cheister** [comment]
This passes for me locally with Java 10 but it looks like travis is having trouble downloading jdks.

**Comment by KengoTODA** [comment]
APT & Travis CI have not supported Java 10 yet.

* https://github.com/travis-ci/travis-ci/issues/9368

**Comment by orihalcon128** [comment]
ASM 6.1: ClassReader.readCode() throws NullPointerException
https://gitlab.ow2.org/asm/asm/issues/317815

**Comment by victorwss** [comment]
@KengoTODA Is this done to be merged?

**Comment by KengoTODA** [comment]
This change has been merged, so SpotBugs 4.0 supports Java10. If SpotBugs 3.1 also needs to support Java10, we need another PR to apply change even to `release-3.1` branch.

**Comment by cheister** [comment]
PR for `release-3.1` is https://github.com/spotbugs/spotbugs/pull/602

**Pull request merged**
