### PR TITLE
Additional keywords to search for SpotBugs preference page (#210)

### PR DESCRIPTION
**Pull request by sewe**
This adds the keywords “bugs“ and “findbugs” to “spotbugs” (the default).

### CODE REVIEW

**Comment by sewe** [comment]
> Please use full qualified name for id attribute, just in case someone woulduse same "keywords" id.

You are right. Mistakenly thought that IDs without dot in them would automatically be prefixed by the plugin ID. But apparently that’s not the case.

**Comment by iloveeclipse** [comment]
Thanks. 
Questions:
1. You seem to manage Eclipse plugin debugging, despite all gradle related issues. Can you please share a short how to (there was old one inside the plugin, you could just update it). 
2. If you plan to provide more patches and intetested, would you like tobe a committer on the project? I have no much free time and it would be nice to have another committer with Eclipse experience on board.

**Comment by iloveeclipse** [comment]
Oops, looks like my approval was not enough to merge. Stupid interface.

**Comment by sewe** [comment]
> 1. You seem to manage Eclipse plugin debugging, despite all gradle related issues. Can you please share a short how to (there was old one inside the plugin, you could just update it).

I’ve got Buildship set up to compile stuff in Eclipse, but I test by building the update site (`./gradlew :eclipsePlugin:build`) and installing into Eclipse with remote debugging enabled. So yeah, I *manage* Eclipse plugin debugging, but have far more experience with Maven/Tycho than with Gradle – and so far, my Gradle experience wasn’t that great.

> 2. If you plan to provide more patches and intetested, would you like tobe a committer on the project? I have no much free time and it would be nice to have another committer with Eclipse experience on board.

I can imagine becoming a committer, yes. I have a few questions in return, however:

1. Does there exist a communication channel to gather opinions among committers? An issue tracker seems less well suited than, say, a mailing list for this.

2. Who is the Gradle expert in residence? Maybe the old FindBugs Ant build was worse, but the build is an area I find very frustrating at the moment – and am not in a position to help much with, as a Gradle newbie.

**Comment by iloveeclipse** [comment]
Currently the communication channel is bug tracker. 
Remote debugging is not an option for me, this is as if using vi instead of IDE. 

Gradle expert should be @jsotuyod, and I'm also not happy about transition from ant - see #153 and #160. Since I have no time to fix this, I have no working setup and so I effectively can't do much anymore on the project, and this is pity. My hope is that @jsotuyod would fix gradle setup sooner or later.

**Pull request merged**
