### PR TITLE
Add windows builds through appveyor

### PR DESCRIPTION
**Pull request by stephengroat**
example: https://ci.appveyor.com/project/stephengroat/spotbugs

### CODE REVIEW

**Comment by iloveeclipse** [comment]
Sorry for asking stupid questions, what is the purpose of this file? Would it add another automated build to every pull request, this time on windows? Why do we need this? To confirm of we are windows compatible?

**Comment by stephengroat** [comment]
yup, you can build on windows. it currently fails on `jdk1.7`, that's why i was including it

**Comment by iloveeclipse** [comment]
Yea, does it mean, *every* pull request will also have to wait for the confirmation from appveyor? BTW Java 7 is not supported for a long time anyway.

**Comment by stephengroat** [comment]
ok, i removed java7.

you can make appveyor blocking or not, at a minimum it can report status back on windows builds

**Comment by KengoTODA** [comment]
currently we have no automatic test for Windows specific solutions (e.g. .bat files), then appveyor isn't so valuable I think.

**Pull request closed without merging**
