### PR TITLE
CWE mapping fixes

### PR DESCRIPTION
**Pull request by gtoison**
Updated some incorrect CWE mappings reported in #3123

### CODE REVIEW

**Comment by davewichers** [comment]
@gtoison - Thanks for this! Looks good. However, there must be a mapping of the rule FI_NULLIFY_SUPER to CWE-586. Can we find that and either remove it or change it to match this change? I'm guessing it's in the definition/implementation of the rule?

**Comment by gtoison** [comment]
`FI_NULLIFY_SUPER` was CWE-586 because the `FI` bugs were all CWE-586 by default:
https://github.com/spotbugs/spotbugs/blob/c4b3fa473d6df297539aa20c57770b90cb9aff52/spotbugs/etc/findbugs.xml#L704

**Comment by davewichers** [comment]
OK. Makes sense. It might make sense to review every FI rule and make sure that rule belongs in either 568, or 586, or maybe neither?? Not sure how many FI rules there are or what they each do.

**Comment by gtoison** [comment]
Thanks, I have mapped FI_MISSING_SUPER_CALL to CWE 568.
Let me know if you find others!

**Comment by davewichers** [comment]
I have reviewed the other FI_ rules and they look fine to me. So I think you can submit this PR for merging by the spotbugs team. If I find other rules that are missing CWEid, or have them wrong, I'll create a separate issue for those, but I think this PR is good to go.

**Review by hazendaz — APPROVED** [review]

**Pull request merged**
