### PR TITLE
Excluded locking on java.lang.Class objects from SSD bug

### PR DESCRIPTION
**Pull request by gonczmisi**
Fixed bug reported by [issue-1978](https://github.com/spotbugs/spotbugs/issues/1978).

SSD bug instance does not get reported if the lock object is from `java.lang.Class`, since there is only a single instance of the class object.

- Extended unit tests with a test case for such scenario
- Aligned `CHANGELOG.md`

### CODE REVIEW

**Review by ThrawnCA — DISMISSED** [review]

**Comment by ThrawnCA** [comment]
Please try to avoid force-pushing, when possible, since it ruins the history.

**Review by ThrawnCA — DISMISSED** [review]

**Comment by gonczmisi** [comment]
> Please try to avoid force-pushing, when possible, since it ruins the history.

Sorry, I rebased locally to resolve conflicts.

**Comment by schlm3** [comment]
would be great to get this into a new release soon...

**Review by KengoTODA — APPROVED** [review]

**Review by KengoTODA — APPROVED** [review]

**Comment by KengoTODA** [comment]
thanks, I will merge this to close #1978.

**Pull request merged**
