### PR TITLE
Update to Gradle 4.9 and spotbugs-maven-plugin 1.6.2 for jdk11 support

### PR DESCRIPTION
**Pull request by stevenschlansker**
Fixes `gradlew` invocation errors on jdk11
https://github.com/gradle/gradle/issues/4515
https://github.com/spotbugs/spotbugs-gradle-plugin/issues/22

### CODE REVIEW

**Comment by henrik242** [comment]
@stevenschlansker Did you take a look at the build problem?

**Comment by henrik242** [comment]
@KengoTODA We should replace the jdk9 build with jdk10

**Comment by stevenschlansker** [comment]
@henrik242 No, I cannot seem to find a jdk9 build - it is already EOL and there is no download on Oracle or OpenJDK that I can see.

Is jdk9 compatibility a goal over jdk10 / 11?  I do not need jdk9 support and so won't be spending much time to explore that.

**Comment by wrprice** [comment]
FYI, JDK 9 builds archived here: http://jdk.java.net/archive/

**Comment by Syquel** [comment]
I think the issue is caused by the `includeNoLocationClasses = true` jacoco flag in [jacoco.gradle](https://github.com/spotbugs/spotbugs/blob/build-on-jdk11/gradle/jacoco.gradle).
It has been explained in the [jacoco issues](https://github.com/jacoco/jacoco/issues/16#issuecomment-351943050) quite well.

I will try it out when I find the time.

**Comment by KengoTODA** [comment]
This issue is closed by #784.

**Pull request closed without merging**
