### PR TITLE
[docs] Update Japanese manual

### PR DESCRIPTION
**Pull request by orihalcon128**
- SpotBugs version number
- Gradle Plugin
- Effort
- Fix typo

### CODE REVIEW

**Comment by KengoTODA** [comment]
Thanks, could you run `build.sh` in `docs` directory? It will reformat po files. Note that your current directory should be `docs`, and `docker` command is required.

**Comment by orihalcon128** [comment]
Working on Windows, not Docker.
No Docker environment.
Built a Sphinx environment on Windows.

Workflow:
- make gettext
- sphinx-intl update -p .build/locale -l ja
- Copy po files to OmegaT source folder
- Translate on OmegaT
- Generate po files by OmegaT (<- format chenged)
- Copy po files to LC_MESSAGES folder from OmegaT target folder
- make -e SPHINXOPTS="-D language='ja'" html
- Commit

**Comment by KengoTODA** [comment]
OK then I will run `docs/build.sh` by own to reformat files, and propose another PR to merge them. Please wait a moment.

**Comment by KengoTODA** [comment]
I found that this script cannot reformat if text in po files aren't updated... I will merge your change.

**Pull request merged**
