### PR TITLE
GH#297 add the full xml headers

### PR DESCRIPTION
**Pull request by xenoterracide**

### CODE REVIEW

**Comment by xenoterracide** [comment]
btw, you might want to put the xsd reference somewhere other than raw git, but that's all I have right now.

**Comment by KengoTODA** [comment]
I think it is ok to use raw git, but it is better to use tag instead of master branch.

**Comment by henrik242** [comment]
> I think it is ok to use raw git, but it is better to use tag instead of master branch.

@xenoterracide Are you looking at this?

**Comment by xenoterracide** [comment]
I don't know what tag I should use, I mean it should basically be the current or next release. I mean I could do one for the existing release... 3.0.x but that has a different path from the 3.1.x so... kind of hard to know what to change it to.

**Comment by henrik242** [comment]
@xenoterracide I'd go for https://raw.githubusercontent.com/spotbugs/spotbugs/3.1.0_RC5/spotbugs/etc/findbugsfilter.xsd

**Pull request merged**
