### PR TITLE
[docs] Generate bug description page not by gradle but by sphinx extension

### PR DESCRIPTION
**Pull request by KengoTODA**
Previously we needed to commit generated files to Git, because readthedocs does not support executing Gradle script before we build HTML pages. By this change, we can stop commiting them to Git.

It also makes possible to translate not only short/long descriptions but also detailed description.

For reviewer: Here is [staging site](http://spotbugs-in-kengo-toda.readthedocs.io/ja/translate-bug-description-page/) to check these changes.

cc @orihalcon128

### CODE REVIEW

**Comment by orihalcon128** [comment]
Source code in "&lt;pre&gt;&lt;code&gt;" block is not formatted.

**Comment by KengoTODA** [comment]
@orihalcon128 English page has the same problem, let me fix in another PR.
http://spotbugs.readthedocs.io/en/latest/bugDescriptions.html#he-class-defines-hashcode-and-uses-object-equals-he-hashcode-use-object-equals

**Comment by iloveeclipse** [comment]
I wonder that the staging page shows some japanese topics next to englisch? I guess this is a bug?

**Comment by KengoTODA** [comment]
@iloveeclipse in which page? could you give me its URL?

**Comment by KengoTODA** [comment]
@orihalcon128 I've prepared fix for that problem:
https://github.com/KengoTODA/spotbugs/compare/translate-bug-description-page...KengoTODA:fix-css-for-multiple-lines-code

staging site: http://spotbugs-in-kengo-toda.readthedocs.io/en/fix-css-for-multiple-lines-code/bugDescriptions.html#he-class-defines-hashcode-and-uses-object-equals-he-hashcode-use-object-equals

I will create another PR after we merge this PR.

**Comment by orihalcon128** [comment]
Source code format is OK.

I want to exclude "deprecated=true".
e.g. TLW_TWO_LOCK_NOTIFY


Hyperlinks in NS_NON_SHORT_CIRCUIT and NS_DANGEROUS_NON_SHORT_CIRCUIT in messages_ja.xml is broken.
I will fix it with another PR.

**Comment by iloveeclipse** [comment]
I'm sorry, I've just used URL from the task description and I see now that this url is pointing to the japanese version of the manual, where half or more of the content seem to be in japanese, happily mixed with englisch. The pure englisch version seem to be OK.

**Comment by KengoTODA** [comment]
@orihalcon128 ok let's exclude them in another pr.

**Comment by KengoTODA** [comment]
@iloveeclipse please approve and merge this pr, orihalcon128 is not SporBugs members for now so he cannot approve.

**Pull request merged**
