### PR TITLE
Minor changes related to classname util methods.

### PR DESCRIPTION
**Pull request by RahulNagekar**
----

Make sure these boxes are checked before submitting your PR -- thank you!

- [x] Added an entry into `CHANGELOG.md` if you have changed SpotBugs code

### CODE REVIEW

**Comment by ThrawnCA** [comment]
Just one thing - can you do a quick check for whether any existing SpotBugs plugins are relying on the return value of the `assertXXX` methods? Eg fb-contrib, findsecbugs, findbugs-guice, MutabilityDetector4FindBugs

**Comment by RahulNagekar** [comment]
Done. Cross checked for usage of ClassName.assertIsDotted and ClassName.assertIsSlashed.
No one is using their return values.

**Comment by RahulNagekar** [comment]
> Just one thing - can you do a quick check for whether any existing SpotBugs plugins are relying on the return value of the `assertXXX` methods? Eg fb-contrib, findsecbugs, findbugs-guice, MutabilityDetector4FindBugs

Done. Cross checked for usage of ClassName.assertIsDotted and ClassName.assertIsSlashed.
No one is using their return values

**Comment by RahulNagekar** [comment]
@ThrawnCA A merge conflict came in today, after resolving that the earlier review automatically got dismissed.
Could you please again do a review, so that I can have this merged?

**Comment by RahulNagekar** [comment]
I am strugling to squash commits and after sync upstream/master keeping only my commit in pull request...hence doing a force -push to solve that.

May be I am not aware of best practices about git and github....again I am learning on my own for these ....It will be really helpful if you could direct me to proper a guide/blog for this.

**Comment by RahulNagekar** [comment]
Also I have a mege in apache/commons but I am not yet added in their contributors list, I wonder how is that. And my commit is also visible to me in that branch. 🤔

**Pull request merged**
