### PR TITLE
[checkstyle] Bump to 10.14.2, remove dependency management to exclude guava

### PR DESCRIPTION
**Pull request by romani**
https://github.com/checkstyle/checkstyle/issues/14211

tested at https://github.com/checkstyle/checkstyle/issues/14211#issuecomment-2002201042

### CODE REVIEW

**Review by hazendaz — APPROVED** [review]

**Comment by hazendaz** [comment]
@romani Thanks!  I appreciate you going extra mile and sending PR for this.

**Comment by romani** [comment]
is it possible to make variable for checksyle version to let me run somthing like
`./gradlew :eclipsePlugin-junit:checkstyleTest -Dcheckstyle.version="${CS_POM_VERSION}"`

I want to add your project to our CI process, to never leak guava again. It is already second time we leak guava.

**Comment by romani** [comment]
meanwhile https://github.com/checkstyle/checkstyle/pull/14671

**Comment by hazendaz** [comment]
> is it possible to make variable for checksyle version to let me run somthing like `./gradlew :eclipsePlugin-junit:checkstyleTest -Dcheckstyle.version="${CS_POM_VERSION}"` ?
> 
> I am ok with any command, where I can specify version of checkstyle in CLI.
> 
> I want to add your project to our CI process, to never leak guava again. It is already second time we leak guava.
> 
> unfortunately I wuold need reference of `mavenLocal` repo in build.gradle ...

Yes I think that is possible.  Actually I think its best practice for a whole host of reasons.  I've opened a ticket to look into it.  Thanks.

**Pull request merged**
