### PR TITLE
Release stable-latest Eclipse plugin to new update site

### LINKED ISSUE #701: Deploy Eclipse plugin to update site on maintenance builds
Right now we deploy Eclipse plugin to daily update site for the master branch only, see `.travis.yml`.

This was OK before we started 4.x on master, but now we see that the most changes are still happening on 3.x branch.

This leads to the problem, that eclipse daily update site never contain "latest" builds from 3.x branch.

I think we should switch it and start pushing to this site from 3.x branch or create eclipse-maintenance-daily update and push on builds to this site.

@KengoTODA : WDYT?

### PR DESCRIPTION
**Pull request by KengoTODA**
URL of new update site will be: https://spotbugs.github.io/eclipse-stable-latest/
This change will close #701.

### CODE REVIEW

**Comment by iloveeclipse** [comment]
:-(

```
Deploying application
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
Still waiting for about 0 seconds
Used disk space: 723M	.
Could not find metadata com.github.spotbugs:spotbugs:3.1.7-SNAPSHOT/maven-metadata.xml in remote (https://oss.sonatype.org/content/repositories/snapshots/)
Could not transfer artifact com.github.spotbugs:spotbugs:jar:3.1.7-20180723.082743-1 from/to remote (https://oss.sonatype.org/content/repositories/snapshots/): Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/com/github/spotbugs/spotbugs/3.1.7-SNAPSHOT/spotbugs-3.1.7-20180723.082743-1.jar. Return code is: 401, ReasonPhrase: Unauthorized.
Could not transfer artifact com.github.spotbugs:spotbugs:pom:3.1.7-20180723.082743-1 from/to remote (https://oss.sonatype.org/content/repositories/snapshots/): Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/com/github/spotbugs/spotbugs/3.1.7-SNAPSHOT/spotbugs-3.1.7-20180723.082743-1.pom. Return code is: 401, ReasonPhrase: Unauthorized.
Could not transfer artifact com.github.spotbugs:spotbugs:zip:3.1.7-20180723.082743-1 from/to remote (https://oss.sonatype.org/content/repositories/snapshots/): Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/com/github/spotbugs/spotbugs/3.1.7-SNAPSHOT/spotbugs-3.1.7-20180723.082743-1.zip. Return code is: 401, ReasonPhrase: Unauthorized.
Could not transfer artifact com.github.spotbugs:spotbugs:jar:javadoc:3.1.7-20180723.082743-1 from/to remote (https://oss.sonatype.org/content/repositories/snapshots/): Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/com/github/spotbugs/spotbugs/3.1.7-SNAPSHOT/spotbugs-3.1.7-20180723.082743-1-javadoc.jar. Return code is: 401, ReasonPhrase: Unauthorized.
Could not transfer artifact com.github.spotbugs:spotbugs:jar:sources:3.1.7-20180723.082743-1 from/to remote (https://oss.sonatype.org/content/repositories/snapshots/): Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/com/github/spotbugs/spotbugs/3.1.7-SNAPSHOT/spotbugs-3.1.7-20180723.082743-1-sources.jar. Return code is: 401, ReasonPhrase: Unauthorized.
Could not transfer artifact com.github.spotbugs:spotbugs:tgz:3.1.7-20180723.082743-1 from/to remote (https://oss.sonatype.org/content/repositories/snapshots/): Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/com/github/spotbugs/spotbugs/3.1.7-SNAPSHOT/spotbugs-3.1.7-20180723.082743-1.tgz. Return code is: 401, ReasonPhrase: Unauthorized.
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':spotbugs:uploadArchives'.
> Could not publish configuration 'archives'
   > Failed to deploy artifacts: Could not transfer artifact com.github.spotbugs:spotbugs:jar:3.1.7-20180723.082743-1 from/to remote (https://oss.sonatype.org/content/repositories/snapshots/): Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/com/github/spotbugs/spotbugs/3.1.7-SNAPSHOT/spotbugs-3.1.7-20180723.082743-1.jar. Return code is: 401, ReasonPhrase: Unauthorized.
```

**Comment by KengoTODA** [comment]
We've successfully pushed contents to https://github.com/spotbugs/eclipse-stable-latest/tree/gh-pages

I'll investigate about SNAPSHOT release

**Comment by iloveeclipse** [comment]
Thanks, is this expected that https://spotbugs.github.io/eclipse-stable-latest/ is still reporting 404 error?

**Comment by KengoTODA** [comment]
GitHub says that 'Your site is published at https://spotbugs.github.io/eclipse-stable-latest/' at https://github.com/spotbugs/eclipse-stable-latest/settings

So I guess that they're working to update CDN or something like that...

**Comment by KengoTODA** [comment]
I also confirmed that Sonatype account/password seems fine. The deployment failure could be some temporal trouble, let me re-trigger build by another PR.

**Comment by iloveeclipse** [comment]
OK, now it is visible. Thanks Kengo. I really appreciate.

**Comment by KengoTODA** [comment]
> I'll investigate about SNAPSHOT release

401 issue hasn't been solved yet. I'll keep investigate about this.

**Pull request merged**
