### PR TITLE
 Fix `com.intellij.diagnostic.PluginException` in IntelliJ SpotBugs plugin

### PR DESCRIPTION
**Pull request by jqyp**
----

Make sure these boxes are checked before submitting your PR -- thank you!

- [x] Added an entry into `CHANGELOG.md` if you have changed SpotBugs code

### CODE REVIEW

**Review by ThrawnCA — APPROVED** [review]

**Review by KengoTODA — CHANGES_REQUESTED** [review]
Please merge the latest `upstream/master` to your topic branch, and solve a conflict in the `CHANGELOG.md` file. Your change itself is LGTM :)

**Comment by KengoTODA** [comment]
I copied stack trace from https://github.com/JetBrains/spotbugs-intellij-plugin/issues/166 here:

```
Do not request resource from classloader using path with leading slash
com.intellij.diagnostic.PluginException: /messages_en_US.xml [Plugin: org.jetbrains.plugins.spotbugs]
at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:504)
at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:471)
at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1401)
at edu.umd.cs.findbugs.PluginLoader.getResource(PluginLoader.java:560)
at edu.umd.cs.findbugs.PluginLoader.addCollection(PluginLoader.java:1279)
at edu.umd.cs.findbugs.PluginLoader.getMessageDocuments(PluginLoader.java:1187)
at edu.umd.cs.findbugs.PluginLoader.init(PluginLoader.java:690)
at edu.umd.cs.findbugs.PluginLoader.(PluginLoader.java:395)
at edu.umd.cs.findbugs.PluginLoader.loadCorePlugin(PluginLoader.java:1442)
at edu.umd.cs.findbugs.PluginLoader.loadInitialPlugins(PluginLoader.java:1396)
at edu.umd.cs.findbugs.PluginLoader.(PluginLoader.java:149)
at org.jetbrains.plugins.spotbugs.common.util.FindBugsCustomPluginUtil$1.compute(FindBugsCustomPluginUtil.java:85)
at org.jetbrains.plugins.spotbugs.common.util.FindBugsCustomPluginUtil$1.compute(FindBugsCustomPluginUtil.java:82)
at org.jetbrains.plugins.spotbugs.common.util.WithPluginClassloader.compute(WithPluginClassloader.java:46)
at org.jetbrains.plugins.spotbugs.common.util.FindBugsCustomPluginUtil.loadTemporary(FindBugsCustomPluginUtil.java:82)
at org.jetbrains.plugins.spotbugs.common.util.FindBugsCustomPluginUtil.loadTemporary(FindBugsCustomPluginUtil.java:72)
at org.jetbrains.plugins.spotbugs.plugins.AbstractPluginLoader.load(AbstractPluginLoader.java:91)
```

@h3xstream I think the problem won't be solved by this PR, but probably it helps IDEA to hide errors in SpotBugs side. Is it OK to merge? 
I don't know why IDEA requests us to 'Do not request resource from classloader using path with leading slash', is there any other solution we have?

Thanks for your help! :+1:

**Comment by jqyp** [comment]
>  I don't know why IDEA requests us to 'Do not request resource from classloader using path with leading slash', is there any other solution we have?

The problem is on the IntelliJ IDEA side. I've seen this message at the beginning of the year. The problem has been [fixed](https://youtrack.jetbrains.com/issue/IDEA-261944), but the [problem occurred again](https://youtrack.jetbrains.com/issue/IDEA-261944#focus=Comments-27-4977663.0-0).

**Comment by KengoTODA** [comment]
I've also checked https://youtrack.jetbrains.com/issue/IDEA-263728 but no luck. I guess we need to reopen open of them...

**Review by ThrawnCA — APPROVED** [review]

**Comment by KengoTODA** [comment]
I'll close this stale PR. 

At least for me, this PR is not solving but hiding the problem. Please keep pushing the IntelliJ idea side.

**Pull request closed without merging**
