### PR TITLE
Access Java classes directly

### LINKED ISSUE #1: missing libs?
looks like asm and bcel jars didn't come over, or am i missing something?

### PR DESCRIPTION
**Pull request by jsotuyod**
- Attempt to fix #1 

Test it on your machine and merge if it works. I know on my machine does, but the old coded did too...

### CODE REVIEW

**Comment by jsotuyod** [comment]
Weird, seema you are not allowed to review and merge. Let me check the config

**Comment by jsotuyod** [comment]
There, check now please

**Comment by jsotuyod** [comment]
There! Now I fixed it for real!

**Comment by mebigfatguy** [comment]
nice

**Pull request merged**
