### PR TITLE
fix FindNonShortCircuit#reportBug

### PR DESCRIPTION
**Pull request by inponomarev**
Fixed `FindNonShortCircuit#reportBug` method based on [static analysis finding](https://www.viva64.com/en/b/0603/#ID0E61EK). `sawNullTestVeryOld` variable had no impact on `priority`.

----

Make sure these boxes are checked before submitting your PR -- thank you!

- [x] Added an entry into `CHANGELOG.md` if you have changed SpotBugs code

### CODE REVIEW

**Comment by KengoTODA** [comment]
I feel this is not critical problem, then let me merge to 4.0 release later.

**Comment by ThrawnCA** [comment]
@inponomarev Can you add unit testing to demonstrate this bug and ensure that it's fixed?

**Comment by inponomarev** [comment]
@ThrawnCA sure I can! how much time do I have before 4.0.0 release?

**Comment by ThrawnCA** [comment]
@inponomarev I doubt that you need to worry about 4.0.0. Bugfixes like this can be incorporated into pretty much any release.

**Comment by inponomarev** [comment]
@ThrawnCA added the unit test -- I had to extract a method to make this function testable. In the unit test itself I had to save/restore global `AnalysisContext` in order not to break the whole build...

**Comment by KengoTODA** [comment]
Now our major branch is `master`, so please rebase your changes and use `master` as the target branch.
I recommend you to create a new PR instead, so I'll close this PR.

**Pull request closed without merging**
