### PR TITLE
Delete redundant put plugin

### PR DESCRIPTION
**Pull request by penguin-wwy**
`putPlugin` funtion be called twice.
PluginLoader.java line 398 and line 1480.
I think be called in 1480 better, then conforms to the mean of `loadCorePlugin`.

### CODE REVIEW

**Comment by ThrawnCA** [comment]
Is this the right target branch?

**Comment by penguin-wwy** [comment]
... Oh, I always use this branch so change it.
Which is latest branch?

**Comment by KengoTODA** [comment]
If this change doesn't affect behaviour, it's OK to put into release-3.1 branch.
If it affects, use master branch for 4.0 release.

**Comment by KengoTODA** [comment]
please merge latest `release-3.1` branch to your branch, and add entry into CHNAGELOG.md.
I think we can use `### Fixed` for this PR, refer [keepachangelog](https://keepachangelog.com/en/1.0.0/) about our CHANGELOG format.

**Pull request merged**
