### PR TITLE
[GHA] Split up build using sonar so it runs against java 21 ubuntu only

### PR DESCRIPTION
**Pull request by hazendaz**
Before opening a 'pull request'

* Search existing issues and pull requests to see if the issue was already discussed.
* Check our discussions to see if the issue was already discussed.
* Check for specific project we support to raise the issue on, under [spotbugs](https://github.com/spotbugs)
* Do not open intellij plugin issues here, open them at [intellij-plugin](https://github.com/JetBrains/spotbugs-intellij-plugin) *

### CODE REVIEW

**Comment by hazendaz** [comment]
Fixes #2857

**Comment by hazendaz** [comment]
merging as this won't see anything on PR but rather after it lands on master.

**Comment by JuditKnoll** [comment]
It seems to fix the problem 😄 
According to the title it looks like you only wanted to run sonar on ubuntu java 21, but there is no check for ubuntu, only for the java version.

**Comment by hazendaz** [comment]
Good catch.  I intended that but couldn't get it to work so I dropped back to jdk check only.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hazendaz** [comment]
Fixed title.

**Pull request merged**
