### PR TITLE
fix: updated RV_01_TO_INT to include float and long

### PR DESCRIPTION
**Pull request by heeki**
Added test class, unit test, and resolution for https://github.com/spotbugs/spotbugs/issues/1518.
----

Make sure these boxes are checked before submitting your PR -- thank you!

- [x] Added an entry into `CHANGELOG.md` if you have changed SpotBugs code

### CODE REVIEW

**Review by ThrawnCA — DISMISSED** [review]

**Review by ThrawnCA — DISMISSED** [review]

**Review by KengoTODA — CHANGES_REQUESTED** [review]
Thanks for suggesting this PR, and please do not forget updating `CHANGELOG.md` :)

**Comment by heeki** [comment]
I have updated changelog.md with the fix. Apologies on the last failed build. I had run `./gradle spotlessApply` but had only committed one of the two files that were updated. I've included the second updated file in the last commit.

**Review by KengoTODA — CHANGES_REQUESTED** [review]
Changes are LGTM. Please add and push your updated `CHANGELOG.md`.

**Review by ThrawnCA — APPROVED** [review]

**Review by KengoTODA — APPROVED** [review]
LGTM. Thanks for your contribution that makes our product and community advanced!

**Pull request merged**
