### PR TITLE
Update dom4j to 2.1.0 to fix 'WARNING: Illegal reflective access by org.dom4j.io.SAXContentHandler' in java 9

### PR DESCRIPTION
**Pull request by cheister**
When running spotbugs in Java 9 you get the following warning:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.dom4j.io.SAXContentHandler (file:dom4j-1.6.1.jar) to method com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser$LocatorProxy.getEncoding()
WARNING: Please consider reporting this to the maintainers of org.dom4j.io.SAXContentHandler
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

This has been fixed in the latest release of dom4j.

### CODE REVIEW

**Comment by KengoTODA** [comment]
It seems that dom4j doesn't provide changelog for v2 releases, and it's hard to check difference by [git diff](https://github.com/dom4j/dom4j/compare/version-2.1.0...dom4j_1_6_1). 

According to [official site](https://dom4j.github.io/), difference between 1.6.1 and 2.1.0 is about generic support and Java8 support. I think we can merge this change because tests aren't broken, how do you think @iloveeclipse?

**Comment by cheister** [comment]
From https://github.com/dom4j/dom4j/releases the release notes are

```
dom4j-2.1.0
Minimum supported version of Java for this branch upgraded to Java 8. Added support for build with Java 9.

dom4j-2.0.2
StringIndexOutOfBoundsException in XMLWriter.writeElementContent() (#26)
TreeNode has grown some generics

dom4j-2.0.1
QName serialization fix (#17)
DocumentException initialize with nested exception (#20)
Accidentally occurring error in a multi-threaded test (#14)

dom4j-2.0.0
compatibility with W3C DOM Level 3 → compatible with Java 5+
use Java generics
sources can be build with JDK 1.5 or newer (implements W3C DOM Level 3)
all classes and interfaces are generified
```

**Comment by KengoTODA** [comment]
Thanks, I didn't notice that page has release notes.

**Comment by jestan** [comment]
+1 Will this be part of 3.1.2 release soon ?

**Comment by henrik242** [comment]
@cheister Could you rebase this against the current `release-3.1`? I fixed a conflict, but there seems to be more to be done (that I'm not able to do in the GH UI).

**Comment by iloveeclipse** [comment]
This PR seem to be a bit broken with the strange merge commit. I've created PR with the original commit cherry picked to 3.1, see #568. Closing this one.

**Comment by henrik242** [comment]
@iloveeclipse I used the GitHub UI to resolve the merge, but it seems to have borked it.  Thanks for cleaning up :)

**Pull request closed without merging**
