### PR TITLE
Bump up ASM to 9.0-beta

### LINKED ISSUE #1229: Fails with OpenJDK 15-ea: Unsupported class file major version 60
It looks like the Maven plug-in needs an update for JDK 15. I get the following error when switching the JDK:

```
     [java] The following errors occurred during analysis:
     [java]   Error scanning java/lang/Object for referenced classes
     [java]     java.lang.IllegalArgumentException: Unsupported class file major version 60
     [java]       At org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
     [java]       At org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
     [java]       At org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
     [java]       At edu.umd.cs.findbugs.asm.FBClassReader.<init>(FBClassReader.java:35)
```

### PR DESCRIPTION
**Pull request by KengoTODA**
close #1229

----

Make sure these boxes are checked before submitting your PR -- thank you!

- [x] Added an entry into `CHANGELOG.md` if you have changed SpotBugs code

### CODE REVIEW

**Comment by KengoTODA** [comment]
> Are we ok with a beta version?

I think so, because its changeset has less changes (just 15 support and three bugfix).
I'll keep this PR open for a while, to welcome opinions from community.

**Comment by iamatgit** [comment]
Won't you need to update spotbugs/jnlp/findbugs.jnlp and spotbugs/src/sampleXml/analysisResultsWithFilterAndUserAnnotations.xml as well?

**Comment by iamatgit** [comment]
Also, the class file version 60 is for JDK 16 (https://hg.openjdk.java.net/jdk/jdk/rev/74571a9cede2).

May I suggest to call update to ASM 9_0_BETA to support JDK 16 (than JDK 15) to be consistent with class file version change and release notes from ASM (https://asm.ow2.io/versions.html). 

Also, please consider to update https://github.com/spotbugs/spotbugs/blob/91e26e6f0fbf2110deedcf5de5a99cdb85bf4ef4/spotbugs/src/main/java/edu/umd/cs/findbugs/classfile/engine/asm/FindBugsASM.java#L31 to Opcodes.ASM10_EXPERIMENTAL

**Comment by KengoTODA** [comment]
Support for JNLP is deprecated #904 so we won't update related files.

**Comment by KengoTODA** [comment]
To use `Opcodes.ASM9_EXPERIMENTAL`, we need to compile our code with `--enable-preview` option.
This option is introduced from Java 11, so we cannot use this experimental feature because we build our code with Java 8.

Let's wait the public stable release for ASM9. I'll find a way to build our solution with Java 11.

**Pull request closed without merging**
