### PR TITLE
Put manual which will be hosted at Read the Docs

### PR DESCRIPTION
**Pull request by KengoTODA**
In [another pull request](https://github.com/spotbugs/spotbugs.github.io/pull/4) I found that Read the Docs helps us to release documentation easily. This pull request will try to add `docs` directory to host source .rst files.

Note that this change contains migration guide for FindBugs 3.0 users. You can check its HTML version at [here](http://spotbugs-in-kengo-toda.readthedocs.io/en/latest/migration.html).
After we merge this pull request, we need to configure Read the Docs to use proper domain.

... BTW I found that we haven't prepared Ant task for SpotBugs. I will try to make a new subproject for it. -> see #113

### CODE REVIEW

**Comment by KengoTODA** [comment]
Updated [Eclipse Plugin part](http://spotbugs-in-kengo-toda.readthedocs.io/en/latest/migration.html#findbugs-eclipse-plugin) in migration guide.

About Maven plugin, we have one problem so please please refer https://github.com/spotbugs/spotbugs/issues/8#issuecomment-276010948

**Comment by KengoTODA** [comment]
@henrik242 Thanks for your review! I've rebased my branch, please check. I also added explanation about how to use SpotBugs with `findbugs-maven-plugin`, it should be available after we merge #125.

**Comment by henrik242** [comment]
Great! I don't want to be picky, but there's still some room for improvement.  There's one commit that says "test", and there's two po file commits that could be squashed together, and generally some more info in the messages would be cool.  Take a look at e.g. https://chris.beams.io/posts/git-commit/#seven-rules

**Comment by KengoTODA** [comment]
@henrik242 Thanks for your merge!

@jsotuyod Could you configure this GitHub repository's WebHook? You can see [how-to at here](http://docs.readthedocs.io/en/latest/webhooks.html#github).

**Comment by jsotuyod** [comment]
@KengoTODA done!

**Comment by KengoTODA** [comment]
Thanks @jsotuyod, now it works! http://spotbugs.readthedocs.io/en/latest/

**Pull request merged**
