### PR TITLE
add support for jakarta namespace

### PR DESCRIPTION
**Pull request by seanmmills**
----

Make sure these boxes are checked before submitting your PR -- thank you!

- [x] Added an entry into `CHANGELOG.md` if you have changed SpotBugs code

### CODE REVIEW

**Comment by seanmmills** [comment]
Resolves https://github.com/spotbugs/spotbugs/issues/2289

**Review by ThrawnCA — APPROVED** [review]

**Comment by hazendaz** [comment]
@seanmmills Will merge but you missed some such as ejb.  Can you double check again all of them and apply any that are missing?  If unsure since not all javax moved, try downloading respective api jars and checking the path.  The ejb one is for sure missing here.

**Comment by seanmmills** [comment]
> @seanmmills Will merge but you missed some such as ejb. Can you double check again all of them and apply any that are missing? If unsure since not all javax moved, try downloading respective api jars and checking the path. The ejb one is for sure missing here.

I think I found all the missing references.  There were quite a few.

**Review by hazendaz — APPROVED** [review]

**Comment by hazendaz** [comment]
Thanks @seanmmills

**Pull request merged**
