### PR TITLE
WIP: Delete jar files from repository

### PR DESCRIPTION
**Pull request by KengoTODA**
Use normal dependency management to depend on other libraries.
Need to modify `distributions` in `findbugs/build.gradle` to keep packaging dependencies into dist zip file.

### CODE REVIEW

**Comment by henrik242** [comment]
@KengoTODA Try rebasing this on the latest `master`

**Comment by henrik242** [comment]
Is this still considered WIP?

**Comment by KengoTODA** [comment]
yes. These diff contains diff in another pill request.

**Comment by henrik242** [comment]
Not anymore :)

**Comment by KengoTODA** [comment]
I'll check why coverage has been decreased.

**Comment by KengoTODA** [comment]
This pull request contains needless changes, so I made new one #109.
Please check that instead.

**Pull request closed without merging**
