### PR TITLE
Reproduce reported problem, and solve it by upgrading BCEL to 6.1

### PR DESCRIPTION
**Pull request by KengoTODA**
Reproduce reported problem as #60.

### CODE REVIEW

**Comment by henrik242** [comment]
This fails locally as well.

**Comment by KengoTODA** [comment]
@henrik242 Sorry I forgot adding WIP label to this PR. To fix this problem, it seems that we need BCEL 6.1. I will ask when it will be released.

**Comment by KengoTODA** [comment]
@garydgregory @mebigfatguy
Hello, do you have the release plan for BCEL 6.1? FindBugs 3.0 has a known bug, and I confirmed that BCEL 6.1-SNAPSHOT can be solution for it. I want to know our next release can depend on BCEL 6.1 or not. 🙇

**Comment by jsotuyod** [comment]
Worst case scenario, we can pin the snapshot release being used and release pointing to it, but it would certainly be better to have a release version as dependency.

**Comment by garydgregory** [comment]
No plan ATM... we need a RM to step forward.

Gary

**Comment by henrik242** [comment]
@garydgregory   RM? Roadmap? Release master? Is there any way we could help speed up the process?

**Comment by mebigfatguy** [comment]
Release manager

-------- Original message --------

**Comment by KengoTODA** [comment]
@mebigfatguy @garydgregory Thanks for your reply! I got it.

@jsotuyod I added a SNAPSHOT jar file from official snapshot repository, and updated metadata such as `MANIFEST.MF`. I'm a beginner for gradle, could you review these diffs?

**Comment by jsotuyod** [comment]
This looks great in general, however, rather than having the jar in the lib directory, you could revert to having it download from the repo as you did in 41c68bbe579967b5c6e9380eee3b826f79c6f000, just change `org.apache.bcel:bcel:6.1-SNAPSHOT` to `org.apache.bcel:bcel:6.1-20161207.023659-9` to have it fixed on that particular build.

**Comment by henrik242** [comment]
@jsotuyod Aren't we risking that the `org.apache.bcel:bcel:6.1-20161207.023659-9` artifact disappears from the repo soon?

**Comment by jsotuyod** [comment]
@henrik242 possible, but most unlikely. People don't usually remove published artifacts, even if they are SNAPSHOTs, and specially not if the stable release has not been published.

**Comment by KengoTODA** [comment]
> just change org.apache.bcel:bcel:6.1-SNAPSHOT to org.apache.bcel:bcel:6.1-20161207.023659-9

I have the same worry with @henrik242: Apache's repository may delete this jar file in near future.

We can see only two built .jar files (build number 8 and 9) in [that SNAPSHOT repo](https://repository.apache.org/content/repositories/snapshots/org/apache/bcel/bcel/6.1-SNAPSHOT/), but BCEL 6.1 has [three closed tickets](https://issues.apache.org/jira/browse/BCEL-284?jql=project%20%3D%20BCEL%20AND%20status%20in%20(Resolved%2C%20Closed)%20AND%20fixVersion%20%3D%206.1%20ORDER%20BY%20priority%20DESC) now, then at least one .jar has been deleted I guess.

**Comment by garydgregory** [comment]
Hi,

You might want to ask on the Apache Commons user ML if someone wants to
volunteer to push out a release.

Gary

**Comment by KengoTODA** [comment]
Or it might be better to postpone merging this pull-request to 3.1.1 or later.
User's project cannot download BCEL 6.1-SNAPSHOT from Maven central, so they need additional task (like us) to use released SpotBugs. It should be not useful for users.

**Comment by henrik242** [comment]
@KengoTODA We could also extract the contents of bcel.jar into spotbugs.jar, but that might not be a desirable solution...

**Comment by mebigfatguy** [comment]
we can always shade the jar. FindBugs made the mistake of using the same package structure, with modified contents.

**Comment by KengoTODA** [comment]
I will try Gradle shadow plugin.

http://imperceptiblethoughts.com/shadow/

**Comment by henrik242** [comment]
@KengoTODA How is the shadow plugin work going?  It would be cool to be able to release this thing :)

**Comment by KengoTODA** [comment]
`503 Service Unavailable` occurred so Travis cannot pass. I will restart job.

https://travis-ci.org/spotbugs/spotbugs/jobs/189727546

**Comment by KengoTODA** [comment]
It seems that `master` is broken. I will check this later.

https://travis-ci.org/spotbugs/spotbugs/jobs/188773189

```

$ ./gradlew build smoketest -S

FAILURE: Build failed with an exception.

* What went wrong:
java.lang.ExceptionInInitializerError (no error message)

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
java.lang.ExceptionInInitializerError
	at org.gradle.initialization.DefaultClassLoaderRegistry.restrictTo(DefaultClassLoaderRegistry.java:40)
	at org.gradle.initialization.DefaultClassLoaderRegistry.restrictToGradleApi(DefaultClassLoaderRegistry.java:36)
	at org.gradle.initialization.DefaultClassLoaderRegistry.<init>(DefaultClassLoaderRegistry.java:30)
	at org.gradle.internal.service.scopes.GlobalScopeServices.createClassLoaderRegistry(GlobalScopeServices.java:215)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:538)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.internal.service.DefaultServiceRegistry.invoke(DefaultServiceRegistry.java:462)
	at org.gradle.internal.service.DefaultServiceRegistry.access$1200(DefaultServiceRegistry.java:84)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryMethodService.invokeMethod(DefaultServiceRegistry.java:796)
	at org.gradle.internal.service.DefaultServiceRegistry$FactoryService.create(DefaultServiceRegistry.java:752)
	at org.gradle.internal.service.DefaultServiceRegistry$ManagedObjectProvider.getInstance(DefaultServiceRegistry.java:589)
	at org.gradle.internal.service.DefaultServiceRegistry$SingletonService.get(DefaultServiceRegistry.java:634)
	at org.gradle.internal.service.DefaultServiceRegistry.applyConfigureMethod(DefaultServiceRegistry.java:253)
	at org.gradle.internal.service.DefaultServiceRegistry.findProviderMethods(DefaultServiceRegistry.java:214)
	at org.gradle.internal.service.DefaultServiceRegistry.addProvider(DefaultServiceRegistry.java:352)
	at org.gradle.internal.service.ServiceRegistryBuilder.build(ServiceRegistryBuilder.java:52)
	at org.gradle.launcher.cli.BuildActionsFactory.createGlobalClientServices(BuildActionsFactory.java:148)
	at org.gradle.launcher.cli.BuildActionsFactory.runBuildWithDaemon(BuildActionsFactory.java:108)
	at org.gradle.launcher.cli.BuildActionsFactory.createAction(BuildActionsFactory.java:83)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.createAction(CommandLineActionFactory.java:249)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:239)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:217)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:33)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:174)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:538)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:538)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:31)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected java.lang.Package[] java.lang.ClassLoader.getPackages() accessible: module java.base does not "opens java.lang" to unnamed module @43599640
	at java.base/jdk.internal.reflect.Reflection.throwInaccessibleObjectException(Reflection.java:427)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:201)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:192)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:186)
	at org.gradle.internal.reflect.JavaMethod.<init>(JavaMethod.java:42)
	at org.gradle.internal.reflect.JavaMethod.<init>(JavaMethod.java:32)
	at org.gradle.internal.reflect.JavaMethod.<init>(JavaMethod.java:36)
	at org.gradle.internal.reflect.JavaReflectionUtil.method(JavaReflectionUtil.java:223)
	at org.gradle.internal.classloader.FilteringClassLoader.<clinit>(FilteringClassLoader.java:48)
	... 47 more



The command "./gradlew build smoketest -S" exited with 1.
```

**Comment by KengoTODA** [comment]
This is reported problem but no solution exists...

https://issues.gradle.org/browse/GRADLE-3565

**Comment by KengoTODA** [comment]
I'll try this: https://github.com/gradle/gradle/issues/1095#issuecomment-270476256

**Comment by KengoTODA** [comment]
I tried to apply `--add-opens` option, but failed.
If you have experience about Java9 jigsaw, please check #101 and help me to make that stable. Thanks in advance 🙏

**Comment by henrik242** [comment]
@KengoTODA Try rebasing this on top of the latest master (and remove the WIP label), maybe we'll get a green build

**Pull request merged**
