### PR TITLE
Release 3.1.0 rc6

### PR DESCRIPTION
**Pull request by KengoTODA**
After we merge this PR, we tag 566d54b or rebased commit then Travis CI will deploy artifacts to Sonatype Nexus, Gradle plugin repository and Eclipse Update Sites. This is the first version to use this deploy automation, I will recover if it fails.

### CODE REVIEW

**Comment by KengoTODA** [comment]
This is the first version to use Travis CI to ship:

1. Gradle Plugin
2. Maven Plugin to Sonatype Nexus
3. Eclipse Plugin to 

I'm checking [build result at Travis CI](https://travis-ci.org/spotbugs/spotbugs/jobs/279418145), to confirm updated .travis.yml works as expected.

**Comment by iloveeclipse** [comment]
@KengoTODA , please don't tag yet. See #400.

**Comment by KengoTODA** [comment]
Got it, I will stop the build and delete tag.

**Comment by KengoTODA** [comment]
[Travis CI is building](https://travis-ci.org/spotbugs/spotbugs/jobs/279433887) newly tagged commit (cherry-pick #401 to 29809e94371b222dea718e15c2cf404a96c35e7f).

**Comment by iloveeclipse** [comment]
@KengoTODA, the tag should be on e703089.

**Comment by KengoTODA** [comment]
@iloveeclipse I've cherry-pick e703089 (your fix) to 29809e9 (which I tagged before), because e703089 uses `3.1.0-SNAPSHOT` as its version and it has "Unreleased" version in CHANGELOG.

**Comment by iloveeclipse** [comment]
Sorry, I can't follow. I don't see neither 3.1.0_RC6 tag nor e7c8920, if I pull with git.

**Comment by KengoTODA** [comment]
It's not in `master` branch. To fetch them, please command `git fetch origin 3.1.0_RC6`.

**Comment by KengoTODA** [comment]
Here is commit graph. It shows that your fix e7c8920e8 is successfully cherry-picked and tagged as 3.1.0_RC6.

```
*       Andrey Loskutov e703089c8  (HEAD -> master) Add all ASM 6 packages to distribution. Fixes #400
*       Kengo TODA      4dd032596  prepare for next development
| *     Andrey Loskutov e7c8920e8  (tag: 3.1.0_RC6) Add all ASM 6 packages to distribution. Fixes #400
|/
*       Kengo TODA      29809e943  release 3.1.0-RC6
*       Kengo TODA      12299125c  fix broken password to sign by GPG
```

**Comment by iloveeclipse** [comment]
I simply can't get why the 3.1.0_RC6 tag is not on master, but on some other branch. It makes no sense for me.

**Comment by KengoTODA** [comment]
I think it's common usage of Git. But you care, so I will fix it by force push to master.

**Comment by iloveeclipse** [comment]
Yes, please.

**Comment by KengoTODA** [comment]
Fixed. Now all related commits are located liner:

```
*       Kengo TODA      77b0f0138  (HEAD -> master) prepare for next development
*       Andrey Loskutov e7c8920e8  (tag: 3.1.0_RC6) Add all ASM 6 packages to distribution. Fixes #400
*       Kengo TODA      29809e943  release 3.1.0-RC6
```

**Comment by iloveeclipse** [comment]
Thanks!

**Pull request merged**
